language: node_js
node_js:
    - "node"
notifications:
    -  email: false
services:
    - postgresql
before_script:
    - psql -c 'create database littlewindowtest;' -U postgres
script:
  - npm run lint
  - npm run testtravis
  - cd client && npm install
  - npm run test --passWithNoTests
  - npm run lint
